/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EncomendasRouteImport } from './routes/encomendas'
import { Route as EmentaRouteImport } from './routes/ementa'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CartaDeVinhosRouteImport } from './routes/carta-de-vinhos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EncomendasRoute = EncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmentaRoute = EmentaRouteImport.update({
  id: '/ementa',
  path: '/ementa',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaDeVinhosRoute = CartaDeVinhosRouteImport.update({
  id: '/carta-de-vinhos',
  path: '/carta-de-vinhos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carta-de-vinhos': typeof CartaDeVinhosRoute
  '/catering': typeof CateringRoute
  '/ementa': typeof EmentaRoute
  '/encomendas': typeof EncomendasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carta-de-vinhos': typeof CartaDeVinhosRoute
  '/catering': typeof CateringRoute
  '/ementa': typeof EmentaRoute
  '/encomendas': typeof EncomendasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carta-de-vinhos': typeof CartaDeVinhosRoute
  '/catering': typeof CateringRoute
  '/ementa': typeof EmentaRoute
  '/encomendas': typeof EncomendasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carta-de-vinhos'
    | '/catering'
    | '/ementa'
    | '/encomendas'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carta-de-vinhos'
    | '/catering'
    | '/ementa'
    | '/encomendas'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carta-de-vinhos'
    | '/catering'
    | '/ementa'
    | '/encomendas'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartaDeVinhosRoute: typeof CartaDeVinhosRoute
  CateringRoute: typeof CateringRoute
  EmentaRoute: typeof EmentaRoute
  EncomendasRoute: typeof EncomendasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encomendas': {
      id: '/encomendas'
      path: '/encomendas'
      fullPath: '/encomendas'
      preLoaderRoute: typeof EncomendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ementa': {
      id: '/ementa'
      path: '/ementa'
      fullPath: '/ementa'
      preLoaderRoute: typeof EmentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta-de-vinhos': {
      id: '/carta-de-vinhos'
      path: '/carta-de-vinhos'
      fullPath: '/carta-de-vinhos'
      preLoaderRoute: typeof CartaDeVinhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartaDeVinhosRoute: CartaDeVinhosRoute,
  CateringRoute: CateringRoute,
  EmentaRoute: EmentaRoute,
  EncomendasRoute: EncomendasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
